build:
  version: "1.0"

productService:
  message: "Welcome to product-service related default profile APIS"
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@eazybank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932
